FROM python:3.9

WORKDIR /app
COPY /requirements/backend.in /app/requirements/backend.in

COPY . /app

RUN pip install -r requirements/backend.in

CMD [ "uvicorn", "spaceship.main:app", "--host=0.0.0.0", "--port=8080" ]