FROM python:3.9

WORKDIR /app2
COPY /requirements/requirements.txt /app2/requirements/requirements.txt
RUN pip install -r requirements/requirements.txt

COPY .gitignore /app2/
COPY build/index.html /app2/build/index.html
COPY /spaceship /app2/spaceship

CMD [ "uvicorn", "spaceship.main:app", "--host=0.0.0.0", "--port=8080" ]